name: Compile IPA App

on:
  workflow_dispatch:

jobs:
  build:
    name: Build TvOS IPA
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 3: Clean the Build Folder
    - name: Clean Build Folder
      run: |
        rm -rf build/

    # Step 4: Build Unsigned IPA file using the Xcode project
    - name: Build Unsigned IPA
      run: |
        xcodebuild -project AMA.MOVIES.xcodeproj \
                   -scheme AMA.MOVIES \
                   -sdk appletvos \
                   -configuration Debug \
                   -archivePath $PWD/build/AMA.MOVIES.xcarchive \
                   clean archive \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   PROVISIONING_PROFILE_SPECIFIER=""

        xcodebuild -exportArchive \
                   -archivePath $PWD/build/AMA.MOVIES.xcarchive \
                   -exportOptionsPlist exportOptions.plist \
                   -exportPath $PWD/build \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   PROVISIONING_PROFILE_SPECIFIER=""

    # Step 4: Upload the IPA as an artifact
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v3
      with:
        name: AMA.MOVIES-IPA
        path: build/*.ipa
